src/Entity/History.php
<?php

namespace App\Entity;

use App\Repository\HistoryRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HistoryRepository::class)]
class History
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $net_value = null;

    #[ORM\Column]
    private ?float $gross_value = null;

    #[ORM\Column(length: 12)]
    private ?string $direction = null;

    #[ORM\Column]
    private ?int $rate = null;

    #[ORM\Column]
    private ?float $value = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNetValue(): ?float
    {
        return $this->net_value;
    }

    public function setNetValue(float $net_value): static
    {
        $this->net_value = $net_value;

        return $this;
    }

    public function getGrossValue(): ?float
    {
        return $this->gross_value;
    }

    public function setGrossValue(float $gross_value): static
    {
        $this->gross_value = $gross_value;

        return $this;
    }

    public function getDirection(): ?string
    {
        return $this->direction;
    }

    public function setDirection(string $direction): static
    {
        $this->direction = $direction;

        return $this;
    }

    public function getRate(): ?int
    {
        return $this->rate;
    }

    public function setRate(int $rate): static
    {
        $this->rate = $rate;

        return $this;
    }

    public function getValue(): ?float
    {
        return $this->value;
    }

    public function setValue(float $value): static
    {
        $this->value = $value;

        return $this;
    }
}

src/Form/Type/CalcType.php
<?php

namespace App\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\PercentType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\LessThanOrEqual;
use Symfony\Component\Validator\Constraints\Positive;

class CalcType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {

        $builder
            ->add('value', MoneyType::class, [
                'currency' => '',
                'constraints' => [
                    new Positive(),
                ],
            ])
            ->add('rate', PercentType::class, [
                'type' => 'integer',
                'constraints' => [
                    new Positive(),
                    new LessThanOrEqual(100),
                ],
            ])
            ->add('calculate', SubmitType::class);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\History;
use App\Enums\Direction;
use App\Form\Type\CalcType;
use App\Repository\HistoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Exception\ORMException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Encoder\CsvEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

class HomeController extends AbstractController
{
    /**
     * @throws ORMException
     */
    #[Route('/', name: 'app_home', methods: ['GET', 'POST'])]
    public function index(
        EntityManagerInterface $entityManager,
        HistoryRepository $repository,
        Request $request): Response
    {
        $form = $this->createForm(CalcType::class, new History());

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $history = $form->getData();
            $value = $history->getValue();
            $rate = $history->getRate();

            $tax = ($rate / 100) * $value;

            $history->setDirection(Direction::NetToGross->value)
                ->setNetValue($value)
                ->setGrossValue(round($value + $tax, 2));

            $entityManager->persist($history);

            $entityManager->flush();

            $history = (new History)
                ->setRate($rate)
                ->setValue($value)
                ->setDirection(Direction::GrossToNet->value)
                ->setNetValue(round($value - $tax, 2))
                ->setGrossValue($value);

            $entityManager->persist($history);

            $entityManager->flush();

            return $this->redirectToRoute('app_home');
        }

        $history = $repository->findAll();

        return $this->render('home/index.html.twig', [
            'form' => $form,
            'history' => $history,
        ]);
    }

    #[Route('/clear', name: 'clear', methods: ['GET'])]
    public function clear(EntityManagerInterface $entityManager,): RedirectResponse
    {
        $query = $entityManager->createQuery(
            'DELETE FROM App\Entity\History e'
        )->execute();

        return $this->redirectToRoute('app_home');
    }

    #[Route('/export', name: 'export')]
    public function export(
        HistoryRepository $repository,
    ): Response {
        $history = $repository->findAll();

        if (empty($history)) {
            return $this->redirectToRoute('app_home');
        }

        $encoders = [new CsvEncoder()];
        $normalizers = array(new ObjectNormalizer());
        $serializer = new Serializer($normalizers, $encoders);
        $csvContent = $serializer->serialize($history, 'csv');

        $response = new Response($csvContent);
        $response->headers->set('Content-Encoding', 'UTF-8');
        $response->headers->set('Content-Type', 'text/csv; charset=UTF-8');
        $response->headers->set('Content-Disposition', 'attachment; filename=sample.csv');

        return $response;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vat Calculator Test{% endblock %}

{% block body %}
    <main>
        <div class="container mx-auto w-9/12 mt-10 border border-slate-200 rounded-md p-4 bg-slate-100 shadow-sm">
            <h1 class="text-center text-slate-600 text-3xl font-bold mb-4">Vat Calculator</h1>

            <h2 class="text-base font-semibold leading-7 text-gray-900">
                This web app calculates vat for any given value at a rate provided in separate input.
            </h2>
            <p class="mt-1 text-sm leading-6 text-gray-600 mb-4">
                Two calculations are triggered when value and rate are submitted.<br>
                First calculation assumes the value provided is a net value, and it calculates gross based on rate provided.<br>
                Second calculation runs assumption that value is gross, and it calculates net value based on a rate provided.<br>
                Results are displayed in a history table below.
            </p>

            {{ form(form) }}

{#            <form action="/calc" method="post">#}
{#                <h2 class="text-base font-semibold leading-7 text-gray-900">#}
{#                    This web app calculates vat for any given value at a rate provided in separate input.#}
{#                </h2>#}
{#                <p class="mt-1 text-sm leading-6 text-gray-600">#}
{#                    Two calculations are triggered when value and rate are submitted.<br>#}
{#                    First calculation assumes the value provided is a net value, and it calculates gross based on rate provided.<br>#}
{#                    Second calculation runs assumption that value is gross, and it calculates net value based on a rate provided.<br>#}
{#                    Results are displayed in a history table below.#}
{#                </p>#}


{#                <div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">#}
{#                    <div class="sm:col-span-3">#}
{#                        <label for="value" class="block text-sm font-medium leading-6 text-gray-900">Value</label>#}
{#                        <div class="mt-2">#}
{#                            <input type="number" step=".01" name="value" id="value" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">#}
{#                        </div>#}
{#                    </div>#}

{#                    <div class="sm:col-span-3">#}
{#                        <label for="rate" class="block text-sm font-medium leading-6 text-gray-900">Rate</label>#}
{#                        <div class="mt-2">#}
{#                            <input type="number" name="rate" id="rate" step=".01" min="0" max="100" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}

{#                <div class="mt-6 flex items-center justify-end gap-x-6">#}
{#                    <button type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Run Calculation</button>#}
{#                </div>#}
{#            </form>#}

            <div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-5 mt-5 shadow-sm rounded ">
                <div class="rounded-t mb-0 px-4 py-3 border-0">
                    <div class="flex flex-wrap items-center">
                        <div class="relative w-full px-4 max-w-full flex-grow flex-1">
                            <h3 class="font-semibold text-base text-blueGray-700">Calculation History</h3>
                        </div>
                        <div class="relative w-full px-4 max-w-full flex-grow flex-1 text-right">
                            <a class="bg-indigo-500 text-white active:bg-indigo-600 text-xs font-bold uppercase px-3 py-1 rounded outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150" type="button" href="{{ path('export') }}">Export</a>
                            <a class="bg-indigo-500 text-white active:bg-indigo-600 text-xs font-bold uppercase px-3 py-1 rounded outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150" type="button" href="{{ path('clear') }}">Clear</a>
                        </div>
                    </div>
                </div>

                <div class="block w-full overflow-x-auto">
                    <table class="items-center bg-transparent w-full border-collapse ">
                        <thead>
                        <tr>
                            <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                                Value
                            </th>
                            <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                                Rate
                            </th>
                            <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                                Net Value
                            </th>
                            <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                                Gross Value
                            </th>
                            <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                                Type
                            </th>
                        </tr>
                        </thead>

                        <tbody>
                        {% for entry in history %}
                        <tr>
                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 ">
                                {{ entry.value }} %
                            </td>
                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 ">
                                {{ entry.rate }} %
                            </td>
                            <td class="border-t-0 px-6 align-center border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                                {{ entry.netValue }}
                            </td>
                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                                {{ entry.grossValue }}
                            </td>
                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                                {{ entry.direction }}
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </main>
{% endblock %}